/* NAME:UJJWAL SHARMA
PURPOSE:TO FIND WHETHER THE NUMBER IS PRIME OR NOTUSING WHILE LOOP */
#include<stdio.h>    //PREPROSESSIVE DIRECTIVE TO INCLUDE STANDARD LIBRARY INPUT OUTPUT HEADER FILE
int main(){		//STARTING OF MAIN PROGRAM
int i=0,j=0;	//DECLARING VARIABLES NAMED "i" AND "j"
int arr[4][3]={{1,2,3},{2,3,4},{3,4,5},{4,5,6}};	//DECLARING 2D MATRIX
for(i=0;i<4;i++){   //FOR LOOP(INITIALIZATION;CONDITION;INCREMENT/DECREMENT)
	for(j=0;j<3;j++){   //FOR LOOP(INITIALIZATION;CONDITION;INCREMENT/DECREMENT)
	printf("arr[%d] [%d] = %d \n",i,j,arr[i][j]);	//PRINT PROGRAM OUTPUT
	}
}
return 0;		//RETURN STATEMENT
}