/*NAME:UJJWAL SHARMA
PURPOSE:TO PRINT HELLO WORLD PROGRAM*/
#include <stdio.h>	//PREPROCESSIVE DIRECTIVE TO INCLUDE STANDARD INPUT OUTPUT HEADER FILE
int main(){	//STARTING THE MAIN PROGRAM 
	printf("Hello World!");		//PRINT THE HELLO WORLD
	return 0;	//RETURN STATEMENT
}
